# CONFIGURATION
cfg.name = AIBrain Experiment
cfg.desc = This is research in Artificial Intelligence.

# TASK
tsk.name = base
tsk.method = inference

# Neural Network
nn.model.type = YuNet
nn.model.backbone.type = YuNetBackbone
nn.model.backbone.stage_channels = [[3, 16, 16], [16, 64], [64, 64], [64, 64], [64, 64], [64, 64]]
nn.model.backbone.downsample_idx = [0, 2, 3, 4]
nn.model.backbone.out_idx = [3, 4, 5]
nn.model.neck.type = TFPN
nn.model.neck.in_channels = [64, 64, 64]
nn.model.neck.out_idx = [0, 1, 2]