# CONFIGURATION
cfg.name = AIBrain YuNet v0
cfg.desc = This is research in YuNet architecture.

# TASK
tsk.name = base
tsk.method = inference

# Neural Network 
nn.model.type = YuNet

# Neural Network's Backbone
nn.model.backbone.type = YuNetBackbone
nn.model.backbone.stage_channels = [[3, 16, 16], [16, 64], [64, 64], [64, 64], [64, 64], [64, 64]]
nn.model.backbone.downsample_idx = [0, 2, 3, 4]
nn.model.backbone.out_idx = [3, 4, 5]

# Neural Network's Neck
nn.model.neck.type = TFPN
nn.model.neck.in_channels = [64, 64, 64]
nn.model.neck.out_idx = [0, 1, 2]

# Neural Network's Bounding Box Head
nn.model.bbox_head.type = YuNet_Head
nn.model.bbox_head.num_classes = 1
nn.model.bbox_head.in_channels = 64
nn.model.bbox_head.shared_stacked_convs = 1
nn.model.bbox_head.stacked_convs = 0
nn.model.bbox_head.feat_channels = 64
nn.model.bbox_head.use_kps = True
nn.model.bbox_head.num_kps = 5

# Neural Network's Bounding Box Head's Prior Generator
nn.model.bbox_head.prior_generator.type = MlvlPointGenerator
nn.model.bbox_head.prior_generator.offset = 0
nn.model.bbox_head.prior_generator.strides = [8, 16, 32]

# Neural Network's Bounding Box Head's Class Loss Function
nn.model.bbox_head.cls_loss.type = CrossEntropyLoss
nn.model.bbox_head.cls_loss.use_sigmoid = True
nn.model.bbox_head.cls_loss.reduction = sum
nn.model.bbox_head.cls_loss.loss_weight = 1.0

# Neural Network's Bounding Box Head's Bounding-Box Loss Function
nn.model.bbox_head.bbox_loss.type = EIoULoss
nn.model.bbox_head.bbox_loss.loss_weight = 5.0
nn.model.bbox_head.bbox_loss.reduction = sum

# Neural Network's Bounding Box Head's Key-points Loss Function
nn.model.bbox_head.kps_loss.type = SmoothL1Loss
nn.model.bbox_head.kps_loss.beta = 0.1111111111111111
nn.model.bbox_head.kps_loss.loss_weight = 0.1

nn.model.bbox_head.obj_loss.type = CrossEntropyLoss
nn.model.bbox_head.obj_loss.use_sigmoid = True
nn.model.bbox_head.obj_loss.reduction = sum
nn.model.bbox_head.obj_loss.loss_weight = 1.0


